export const PROTOCOLS = [
  {
    id: "base-weekday",
    name: "Default Weekday",
    description: "Standard weekday structure covering all core rhythm blocks.",
    category: "base",
    active: true,
    days: [0, 1, 2, 3, 4],
    mode: "replace",
    blocks: "Wake 6:30 → Meal 8:00 → Deep Work 9:00–11:00 → Task Block 11:00–1:00 → Meal 1:00 → Outreach 2:00–3:00 → Processing 3:00–4:30 → Deep Work 5:00–7:00 → Meal 7:00 → Wind Down 9:00 → Sleep 10:30",
    dateRange: null,
    protoKeys: ["wake", "meal1", "meal2", "meal3", "task", "deep1", "deep2", "outreach", "processing", "winddown", "sleep"],
  },
  {
    id: "wed-workout",
    name: "Wednesday Workout Window",
    description: "Adds a movement block on Wednesdays. Merges with the base weekday protocol.",
    category: "daySpecific",
    active: true,
    days: [2],
    mode: "merge",
    blocks: "Movement 7:00–8:00",
    dateRange: null,
    protoKeys: ["movement"],
  },
  {
    id: "weekend-rhythm",
    name: "Weekend Rhythm",
    description: "Lighter weekend structure with flexible deep work and social time.",
    category: "daySpecific",
    active: false,
    days: [5, 6],
    mode: "replace",
    blocks: "",
    dateRange: null,
    protoKeys: [],
  },
  {
    id: "edge-city",
    name: "Edge City",
    description: "Full schedule override for the Edge City residency period.",
    category: "exception",
    active: false,
    days: [],
    mode: "replace",
    blocks: "",
    dateRange: "May 30 – Jun 27",
    protoKeys: [],
  },
];

export const TASKS = [
  {
    id: "task-1",
    name: "Send pitch deck to Luminate",
    deadline: "2026-05-07T17:00:00.000Z",
    category: "urgent",
    done: false,
    createdAt: "2026-05-05T09:00:00.000Z",
  },
  {
    id: "task-2",
    name: "File Q1 expense report",
    deadline: "2026-05-08T23:59:00.000Z",
    category: "urgent",
    done: false,
    createdAt: "2026-05-04T14:30:00.000Z",
  },
  {
    id: "task-3",
    name: "Draft Edge City session outline",
    deadline: "2026-05-15T12:00:00.000Z",
    category: "work",
    done: false,
    createdAt: "2026-05-05T10:00:00.000Z",
  },
  {
    id: "task-4",
    name: "Update Civic Sandbox landing page copy",
    deadline: null,
    category: "work",
    done: false,
    createdAt: "2026-05-03T08:00:00.000Z",
  },
  {
    id: "task-5",
    name: "Renew domain registration",
    deadline: "2026-05-20T00:00:00.000Z",
    category: "admin",
    done: false,
    createdAt: "2026-05-01T11:00:00.000Z",
  },
  {
    id: "task-6",
    name: "Book flights for June residency",
    deadline: "2026-05-12T00:00:00.000Z",
    category: "admin",
    done: true,
    createdAt: "2026-04-28T09:00:00.000Z",
  },
  {
    id: "task-7",
    name: "Pick up whiteboard markers + sticky notes",
    deadline: null,
    category: "shopping",
    done: false,
    createdAt: "2026-05-06T07:30:00.000Z",
  },
];

export const OUTREACH = [
  {
    id: "out-1",
    person: "Allan Madoc",
    context: "Intro'd at Civic Future summit. Exploring co-design residency model together.",
    lastTouch: "2026-04-28",
    nextAction: "Send him the modular writing system draft for feedback",
    resurface: "today",
    status: "today",
    done: false,
  },
  {
    id: "out-2",
    person: "Gary Dillabough",
    context: "Potential anchor funder for Civic Sandbox. Met via Omar intro.",
    lastTouch: "2026-04-20",
    nextAction: "Follow up on Q2 funding conversation — ask for 30-min call",
    resurface: "2026-05-09T00:00:00.000Z",
    status: "active",
    done: false,
  },
  {
    id: "out-3",
    person: "Brandon Roul",
    context: "Creative technologist. Wants to collaborate on the Composition dashboard UI.",
    lastTouch: "2026-04-10",
    nextAction: "Waiting for him to send over his portfolio / availability",
    resurface: "2026-05-14T00:00:00.000Z",
    status: "waiting",
    done: false,
  },
  {
    id: "out-4",
    person: "Omar Ababneh",
    context: "Long-time collaborator. Introduced Gary. Haven't connected in a while.",
    lastTouch: "2026-03-15",
    nextAction: "Reconnect — share what's been built since March",
    resurface: "2026-05-20T00:00:00.000Z",
    status: "dormant",
    done: false,
  },
];

export const EVENTS = [
  {
    id: "evt-1",
    name: "Civic Sandbox team standup",
    time: "10:00",
    duration: 30,
    date: "2026-05-06",
    category: "collab",
    section: "today",
    tlRowId: "task",
  },
  {
    id: "evt-2",
    name: "Call with Allan Madoc",
    time: "14:00",
    duration: 45,
    date: "2026-05-06",
    category: "networking",
    section: "today",
    tlRowId: "outreach",
  },
  {
    id: "evt-3",
    name: "Music session — composition sketches",
    time: "19:00",
    duration: 90,
    date: "2026-05-06",
    category: "music",
    section: "today",
    tlRowId: "deep2",
  },
  {
    id: "evt-4",
    name: "Edge City orientation call",
    time: "11:00",
    duration: 60,
    date: "2026-05-09",
    category: "work",
    section: "week",
    tlRowId: null,
  },
  {
    id: "evt-5",
    name: "Dinner with Gary Dillabough",
    time: "19:30",
    duration: 120,
    date: "2026-05-10",
    category: "social",
    section: "week",
    tlRowId: null,
  },
  {
    id: "evt-6",
    name: "Luminate pitch presentation",
    time: "15:00",
    duration: 60,
    date: "2026-05-20",
    category: "work",
    section: "upcoming",
    tlRowId: null,
  },
];

export const TODAY_OUTCOME = {
  text: "",
  resolved: false,
  carriedOver: false,
};

export const TOMORROW_GOAL = {
  text: "",
  set: false,
};
